version: '3.8'

services:
  
  app:
    build:
      context: .
      dockerfile: src/SwaggerDemo.HttpApi.Host/Dockerfile
    image: myproject:latest
    ports:
      - "5001:80"
    environment:
      - ConnectionStrings__Default=Server=sqlserver,1433;Database=SwaggerDemoDb;User Id=sa;Password=YourStrong@Passw0rd;Encrypt=False;TrustServerCertificate=True;
      - Redis__Configuration=redis:6379
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
    container_name: sqlserver_container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Passw0rd", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10