version: "3.8"

services:

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    # command: -config.file=/etc/loki/local-config.yaml
    # volumes:
    #   - ./loki/loki.yml:/etc/loki/local-config.yaml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./promtail/promtail.yml:/etc/promtail/promtail.yml
      - /Users/nizar/SwaggerDemo/Logs:/Users/nizar/SwaggerDemo/Logs:ro
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - monitoring
    env_file:
      - .env.host

  zebkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - monitoring

  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"
      - "9412:9411"
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo/tempo.yaml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring

networks:
  monitoring:




# version: "3.8"
# services:

#   prometheus:
#     image: prom/prometheus
#     ports:
#       - "9090:9090"
#     volumes:
#       - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#     networks:
#       - monitoring

#   loki:
#     image: grafana/loki:2.9.0
#     ports:
#       - "3100:3100"
#     command: -config.file=/etc/loki/local-config.yaml
#     networks:
#       - monitoring

#   zebkin:
#     image: openzipkin/zipkin
#     ports:
#       - "9411:9411"
#     networks:
#       - monitoring

#   tempo:
#     image: grafana/tempo:latest
#     ports:
#       - "3200:3200"
#       - "9412:9411" # Important: 9412 intern for tempo to receive zipkin from zebkin
#     command: ["-config.file=/etc/tempo/tempo.yaml"]
#     volumes:
#       - ./tempo/tempo.yaml:/etc/tempo/tempo.yaml
#     networks:
#       - monitoring

#   grafana:
#     image: grafana/grafana
#     ports:
#       - "3000:3000"
#     environment:
#       - GF_SECURITY_ADMIN_USER=admin
#       - GF_SECURITY_ADMIN_PASSWORD=admin
#     volumes:
#       - ./grafana/provisioning:/etc/grafana/provisioning
#     networks:
#       - monitoring

#   promtail:
#     image: grafana/promtail:2.9.0
#     container_name: promtail
#     volumes:
#       - /var/log:/var/log  # Collecte des logs du système
#       - ./promtail/config.yml:/etc/promtail/config.yml  # Fichier de configuration pour Promtail
#     command: -config.file=/etc/promtail/config.yml
#     networks:
#       - monitoring

# networks:
#   monitoring:
