version: '3.8'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Passw0rd", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  dbmigrator:
    build:
      context: ./
      dockerfile: src/SwaggerDemo.DbMigrator/Dockerfile
    image: dbmigrator:latest
    environment:
      - ConnectionStrings__Default=Server=sqlserver,1433;Database=SwaggerDemoDb;User Id=sa;Password=YourStrong@Passw0rd;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_started  
    entrypoint: ["/bin/sh", "-c", "sleep 10 && dotnet SwaggerDemo.DbMigrator.dll"]

  authserver:
    build:
      context: ./
      dockerfile: src/SwaggerDemo.AuthServer/Dockerfile
    image: authserver:latest
    ports:
      - "5002:80"
    environment:
      - ConnectionStrings__Default=Server=sqlserver,1433;Database=SwaggerDemoAuthDb;User Id=sa;Password=YourStrong@Passw0rd;Encrypt=False;TrustServerCertificate=True;
      - Redis__Configuration=redis:6379
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_started
      dbmigrator:
        condition: service_completed_successfully

  app:
    build:
      context: ./
      dockerfile: src/SwaggerDemo.HttpApi.Host/Dockerfile
    image: myproject:latest
    ports:
      - "5001:80"
    environment:
      - ConnectionStrings__Default=Server=sqlserver,1433;Database=SwaggerDemoDb;User Id=sa;Password=YourStrong@Passw0rd;Encrypt=False;TrustServerCertificate=True;
      - Redis__Configuration=redis:6379
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_started
      dbmigrator:
        condition: service_completed_successfully
      authserver:
        condition: service_started





# version: '3.8'

# services:

#   sqlserver:
#     build:
#       context: ./
#       dockerfile: Dockerfile.sqlserver
#     container_name: sqlserver_container
#     ports:
#       - "1433:1433"
#     environment:
#       SA_PASSWORD: "YourStrong@Passw0rd"
#       ACCEPT_EULA: "Y"
#     healthcheck:
#       test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Passw0rd", "-Q", "SELECT 1"]
#       interval: 10s
#       timeout: 5s
#       retries: 10

#   app:
#     build:
#       context: ./
#       dockerfile: src/SwaggerDemo.HttpApi.Host/Dockerfile
#     image: myproject:latest
#     ports:
#       - "5001:80"
#     environment:
#       - ConnectionStrings__Default=Server=sqlserver,1433;Database=SwaggerDemoDb;User Id=sa;Password=YourStrong@Passw0rd;Encrypt=False;TrustServerCertificate=True;
#       - Redis__Configuration=redis:6379
#     depends_on:
#       sqlserver:
#         condition: service_healthy
#       redis:
#         condition: service_started
#       dbmigrator:
#         condition: service_completed_successfully

#   dbmigrator:
#     build:
#       context: ./
#       dockerfile: src/SwaggerDemo.DbMigrator/Dockerfile
#     image: dbmigrator:latest
#     environment:
#       - ConnectionStrings__Default=Server=sqlserver,1433;Database=SwaggerDemoDb;User Id=sa;Password=YourStrong@Passw0rd;Encrypt=False;TrustServerCertificate=True;
#     depends_on:
#       sqlserver:
#         condition: service_healthy
#       redis:
#         condition: service_started  
#     entrypoint: ["/bin/sh", "-c", "sleep 10 && dotnet SwaggerDemo.DbMigrator.dll"]

#   redis:
#     image: redis:latest
#     container_name: redis
#     ports:
#       - "6379:6379"
#     restart: always




  # app-HttpApi.Host:
  #   build:
  #     context: ./
  #     dockerfile: src/SwaggerDemo.HttpApi.Host/Dockerfile
  # AuthServer:
  #   build:
  #     context: ./
  #     dockerfile: src/SwaggerDemo.AuthServer/Dockerfile
  # DbMigrator:
  #   build:
  #     context: ./
  #     dockerfile: src/SwaggerDemo.DbMigrator/Dockerfile