global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'aspnetcore-app'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:44397']
