name: Build and SonarQube Analysis

on:
  push:
    branches:
      - main       

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Install SonarScanner for .NET
      run: |
        dotnet tool install --global dotnet-sonarscanner
  
    - name: Start SonarQube Analysis
      run: |
        dotnet sonarscanner begin /k:"my-new-project-key" /d:sonar.host.url= ${{ secrets.SONAR_HOST_URL }}  /d:sonar.login= ${{secrets.SONAR_TOKEN}}  /d:sonar.scanner.scanAll=false
        dotnet build

    - name: End SonarQube Analysis        
      run: |
        dotnet sonarscanner end /d:sonar.login=${{secrets.SONAR_TOKEN}} 





